name = ['上海','深圳','云南','广东','北京','大理','丽江']  
print(name)  
print(sorted(name))  
print(name)  
print(sorted(name,reverse = True))  
print(name)  
name.reverse()  
print(name)   
name.reverse()  
print(name)  
name.sort()   
print(name)  
name.sort(reverse=True)  
# print(sites.sort(reverse=True))  
print(name)  
