name = input("请输入你的姓名:")
age = int(input("请输入你的年龄:"))
sex = input("请输入你的性别:")
high = int(input("请输入你的身高:"))
ID_number = int(input("请输入你的身份证号码:"))
education = input("请输入你的学历:")
birthday = input("请输入你的生日:")
phone = int(input("请输入你的手机号:"))
print('姓名 %s'%name,'年龄 %d'%age,'sex %s'%sex,'身高 %d'%high,'身份证号 %d'%ID_number,'学历 %s'%education,'生日 %s'%birthday,'手机号 %d'%phone)
